### PR TITLE
Add server side time verification

### PR DESCRIPTION
**Pull request by martijnckx**
Env var `APPWRITE_COLLECTION_SESSIONS_ID` should be set to `sessions`.

This PR adds sessions that record time server side, and check if the time you send to the leaderboards is close to the time we recorded on the server.

Times can definitely still be cheated, but now you need to send `/api/start`, some X time later `/api/stop` and then send in a leaderboard entry with a time that (almost) matches the time between your start and stop calls. This makes cheating harder, you can no longer just edit the time in the request body. You actually need to time some stuff now 😊. And also can't be fully programmatic, since the robots check from previous PR prevents robots from submitting a time to the leaderboards.

### CODE REVIEW

**Comment by ErwinAI** [comment]
Cool, looks good. Probs need to start handling some of the errors in the UI but don't think it's likely a false positive occurs anyway so meh 📦

**Comment by martijnckx** [comment]
I agree, but didn't want to meddle in your UI flow yet, wanted my security changes to be as invisible as possible 😄

**Comment by martijnckx** [comment]
Seems like in prod 0.3 sec isn't enough margin to clear the network delays etc. My test was:

Client side timer: 3.518800000000745
Server side time: 3.861 (+0.3579)

I'll bump it to 0.5, or do you want it configurable in an env var @ErwinAI?

**Comment by martijnckx** [comment]
@ErwinAI created a PR #10 where I bumped the margin to 0.5 hard coded.

**Pull request merged**
