### PR TITLE
Add robots verification with Turnstile

### PR DESCRIPTION
**Pull request by martijnckx**
Adds an invisible Turnstile (like captcha) and verifies it on the server when submitting a score to the leaderboards. This prevents people from sending requests without using the front end as a human.

`NUXT_PUBLIC_TURNSTILE_SITE_KEY` and `TURNSTILE_SECRET_KEY` environment variables need to be added. While testing, you can use these (or other ones to test scenarios where the check should fail, as explained on the [Turnstile Testing docs](https://developers.cloudflare.com/turnstile/troubleshooting/testing/)):

```
NUXT_PUBLIC_TURNSTILE_SITE_KEY=1x00000000000000000000BB
TURNSTILE_SECRET_KEY=1x0000000000000000000000000000000AA
```

For production values, I created a Turnstile to use and will send the keys to Erwin by email. You can also [create your own Turnstile widget in Invisible mode](https://developers.cloudflare.com/turnstile/get-started/#get-a-sitekey-and-secret-key) if you prefer.

I'll add some additional checks later today in separate PRs.

### CODE REVIEW

**Comment by ErwinAI** [comment]
Code looks good, thank you for helping out!

When running with `npm run dev-expose` I get the following error from turnstile after trying to submit my code, though:

```Turnstile Widget seem to have crashed:  1kss0```
Might be something I'm doing wrong?

And I seem to be a bot so it's a false positive:

image


Initially I get `Uncaught TurnstileError: [Cloudflare Turnstile] Error: 110200.`, then afterwards `Uncaught TurnstileError: [Cloudflare Turnstile] Error: 300030.` multiple times.

**Comment by martijnckx** [comment]
@ErwinAI which environment variables are you using locally? The `110200` means "domain not allowed", so it looks like you're using the production variables locally. That indeed won't work (only host `4242.pro` is allowed on those). Try using [testing keys](https://developers.cloudflare.com/turnstile/troubleshooting/testing/) locally and let me know if that works? There's different testing keys that will always succeed / fail to test different scenarios.

If there is a testing/acceptance domain, I can add that to the allowed domains of the production keys so we can test a non-local environment if you like?

Also, FYI, you don't need to use `dev-expose` if you don't want/need it. I just test security stuff through an annoying browser that can't directly reach `localhost` (hence I need `--host 0.0.0.0` to expose to all interfaces).

**Comment by martijnckx** [comment]
@ErwinAI here's a recording (45 seconds) of me going from repo clone to submitted score on this branch, so all should work: https://img.ckx.be/8BSGCgqr (since I show env vars here, password is the nuxt secret share key env var 😉)

**Comment by ErwinAI** [comment]
Clear, my bad, I was indeed using prod data in local env. Checked again and it works properly :)
Hope this helps security wise. I notice there are still quite a few scores that seem impossible. It seems overkill but perhaps sending off each keystroke and replicating the result + the time (and validate it) server-side would be best 🙈

I've just merged this PR and it's live now :) Thank you @martijnckx !🙌

**Comment by martijnckx** [comment]
Yeah I didn't end up having time yesterday, but I'll try something that does some time-checking verification today. If that's not enough we can consider the sending-all-keystrokes route I guess 😅.

I'd need to store some timestamps / session stuff. (How) can I add documents/databases to Node Appwrite @ErwinAI?

**Comment by ErwinAI** [comment]
I'll send you an email in a bit about appwrite

**Pull request merged**
